GET http://localhost:5000/auth/currentUser
Content-Type: application/json

###

GET http://localhost:5000/prompt/latest
Content-Type: application/json

###

POST http://localhost:5000/prompt/
Content-Type: application/json